version = 1

provider = "gemini"
timeout = 90000

[gemini]
key = "YOUR_GEMINI_API_KEY"
model = "gemini-2.5-flash"
temperature = 0.0
top_p = 0.95
top_k = 64
max_output_tokens = 65536
thinking_budget = 0

[prompt]
proof = "Proofread the following."
slack = "Proofread and improve Slack message."
sum = "Summarize the following."

de = "Translate the following into German."
en = "Translate the following into US English."
fr = "Translate the following into French."
hr = "Translate the following into Croatian."
it = "Translate the following into Italian."

expl = "Explain the following."
impl = "Implement the following."
rmc = "Remove comments."

commit = """
Write a conventional commit message in the following form.

type(optional scope): description

[optional body]

[optional footer(s)]

Use one of the following types: feat, fix, build, chore, ci, docs, perf, refactor, style, test.

Start the description with a lowercase letter and use the imperative mood.

Write the optional body using complete sentences, proper case, and the imperative mood.

To signify a breaking change, append an ! immediately before the : in the header. A commit with an ! in the header MUST include a BREAKING CHANGE: footer.

Start the footer with BREAKING CHANGE: followed by a colon and a space. After the prefix, explain the breaking change, what it affects, and what migration steps are necessary.
"""

review = """
Please review the following.

Suggest improvements and explain your reasoning for each suggestion.
"""
